### ISSUE TITLE
Schnittstellenrealisierung: api/task/edit

### ISSUE THREAD

**Issue by bzenz** [Freywood/GradeMe#56]
Bearbeiten einer Task. Nur die übergebenen Parameter sollen überschrieben werden. Fehlermeldung, falls die Task nicht existiert. 

Als Beispiel kann evaluateTask genommen werden, da dort auch evaluations bearbeitet werden, falls diese bereits existieren.

**Comment by Doubrixel** [comment]
Nach merge, Robin bescheid geben dass er sein Issue #71 testen kann
