### ISSUE TITLE
Kursnamen anpassen

### ISSUE THREAD

**Issue by Doubrixel** [Freywood/GradeMe#72]

**Comment by bzenz** [comment]
Das Backend übergibt die Kursnamen nun bei folgenden Schnittstellen:
- `/api/task/getAll/forCourse`
- `/api/task/getAll/forUser`
- `/api/evaluation/getAll/forUser`
- `/api/course/create`
- `/api/course/getAll/forUser`

**Comment by bzenz** [comment]
Zudem wurde bei der Gelegenheit der Rückgabeparameter `course` zu `courseId` bei folgenden Schnittstellen umbenannt:

- `/api/task/getAll/forCourse`
- `/api/task/getAll/forUser`
- `/api/evaluation/getAll/forUser`

Bitte entsprechende Anpassungen direkt im Frontend übernehmen.

**Comment by bzenz** [comment]
Bei Unklarheiten: [hier](https://github.com/Freywood/GradeMe/pull/117/files) die Änderungen für #117 (Kursnamen im Backend generieren) oder in der [Schnittstellendoku](https://github.com/Freywood/GradeMe/blob/master/Dokumentation/Der%20Rest/schnittstellen.txt) nachlesen.
