### ISSUE TITLE
Aufgabenbewertung aus Kurs herraus führt zu falscher Anzeige anschließend

### ISSUE THREAD

**Issue by Blackie11elf** [Freywood/GradeMe#83]
Nach dem Bewerten einer Aufgabe in der Aufgabenübersicht für einen Kurs kommt man nach dem submitten in die generelle Aufgabenansicht für den Lehrer

**Comment by Doubrixel** [comment]
Kann ich so nicht reproduzieren. Jedoch wird wenn ich in der generellen Aufgabenübersicht etwas bewerte danach die Aufgabenübersicht für einen Kurs angezeigt. 

Jetzt ist es so implementiert, dass die Aufgabenübersicht, die vorher geöffnet war aufgerufen wird
